---
# Bad ansible! This playbook is an example of poor/bad practices!
# Bad practices may include:
#
#   Poor formatting and structure
#   Poor use of YAML - but good enough to parse
#   Inconsistent style
#   Incorrect use of modules
#   Poor module choice
#   Unclear names
#   Hard coding / poor use of variables
#   Roles - what are roles?
#   Bare variables
#   No use of handlers

- name: configuration
  hosts: all
  gather_facts: false # remove later! speeds up testing
  become: true

  tasks:
  # - name: enable repos from open_three-tier-app.repo
  #   template:
  #     src: open_three-tier-app.repo
  #     dest: /etc/yum.repos.d/open_three-tier-app.repo
  #     mode: 0644

  - name: Configure OpenTLC yum repos
    copy:
      src: open_three-tier-app.repo
      dest: /etc/yum.repos.d/open_three-tier-app.repo
      mode: u=rw,go=r

- name: include haproxy_tasks.yml file
  import_playbook: haproxy_tasks.yml

- name: include tomcat_tasks.yml file
  import_playbook: tomcat_tasks.yml

- name: include postgres_tasks.yml file
  import_playbook: postgres_tasks.yml

#NOTE: code below does nothing
# - name: deploy apache
#   hosts: apps
#   gather_facts: false
#   become: true


#   tasks:
#   - name: Install Apache package with Yum
#     yum:
#       name: httpd
#       state: latest

#   - name: Enable Apache at boot
#     service:
#       name: httpd
#       enabled: yes
#       state: started  #TODO: This line might not be wanted?...

# #  - name: start apache
# #    service:
# #      name: httpd
# #      state: started
