#TODO: Figureout which of these host params below are correct
- name: deploy postgres
  #hosts: apps
  gather_facts: false
  become: true
  hosts: appdbs

  tasks:
  - name: Install postgres-server package with Yum
    yum:
     name: postgresql-server
     state: latest

  - name: enable apache at boot
    service:
      name: postgresql
      enabled: yes

  - name: tell user to finish setting up postgres
    debug:
      msg: "Either uncomment the postgres setup or manually login and initialize"

#TODO: Figure out best way to make sure postgres database is initialized
  - name: start postgres
    service:
      name: postgresql.service
      state: started
    register: postgres_service_info
    ignore_errors: yes

  - when: postgres_service_info.failed #and postgres_service_info.changed == 'false'
    block:
      - name: debug inside of block
        debug:
          msg: "HI FROM CONDITIONAL BLOCK!"

 # only run the next 2 tasks once!
      - name: initilize postgres
        command: postgresql-setup initdb

      - name: initilize postgres some more
        command: chkconfig postgresql on

      - name: start postgres
        service:
          name: postgresql.service
          state: started
        register: postgres_service_info


  - name: Debug postgres.service info
    debug:
      var: postgres_service_info